---
title: "Prediction Assignment"
author: "Justin Meyer"
date: "January 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

# Get data

testing <- read.csv("pml-testing.csv")
training <- read.csv("pml-training.csv")

# The outcome to predict is classe
summary(training$classe)

# Review the available data
str(training)

# Select a subset of variables to use
training <- subset(training, 
                   select = c("classe", 
                              "roll_belt", "pitch_belt", "yaw_belt", "total_accel_belt",
                              "roll_arm", "pitch_arm", "yaw_arm", "total_accel_arm",
                              "roll_dumbbell", "pitch_dumbbell", "yaw_dumbbell", "total_accel_dumbbell",
                              "roll_forearm", "pitch_forearm", "yaw_forearm", "total_accel_forearm"))

# Summarize selected variables
summary(training)

# Create model
library(caret)
rf_fit <- train(classe ~ ., data = training, 
                 method = "rf")

rf_fit

predict(rf_fit, testing)

```
